#ifndef __MAPS_ROBOTML_DATATYPES_H__
#define __MAPS_ROBOTML_DATATYPES_H__

#include "robotml/maps_robotml_primitive_datatypes.h"


/*******************************************/
/* COMPOSED DATA TYPES FORWARD DECLARATIONS*/
/*******************************************/

class Header;
class MultiArrayDimension;
class MultiArrayLayout;
class ByteMultiArray;
class ColorRGBA;
class Float32MultiArray;
class Int32MultiArray;
class Int8MultiArray;
class Int16MultiArray;
class Int64MultiArray;
class Float64MultiArray;
class UInt64MultiArray;
class UIint16MultiArray;
class UInt32MultiArray;
class UInt8MultiArray;
class DiagnosticArray;
class KeyValue;
class DiagnosticStatus;
class Point;
class Point32;
class PointStamped;
class Polygon;
class PolygonStamped;
class Vector3;
class Vector3Stamped;
class Quaternion;
class Pose;
class PoseStamped;
class TwistWithCovariance;
class TwistStamped;
class Twist;
class PoseWithCovariance;
class Pose2D;
class PoseWithCovarianceStamped;
class PoseArray;
class QuaternionStamped;
class Transform;
class WrenchStamped;
class Wrench;
class Path;
class Odometry;
class MapMetaData;
class OccupancyGrid;
class GridCells;
class RegionOfInterest;
class Range;
class CameraInfo;
class Imu;
class LaserScan;
class Image;
class ChannelFloat32;
class CompressedImage;
class PointCloud;
class PointField;
class PointCloud2;
class JointState;
class NavSatStatus;
class NavSatFix;
class Joy;
class JoyFeedback;
class JoyFeedbackArray;
class CarLikeOdometry;
class DifferentialOdometry;
class COVARIANCE_TYPE;
class SERVICE_TYPE;
class STATUS_TYPE;
class GoalID;
class GoalStatus;
class GoalStatusArray;
class Velocity_Linear;
class Art_Set_Point;
class Distance;
class Metric;
class Angular;
class Velocity_Angular;
class Op_Set_Point;
class Speed_Tics_Left_Right;
class Speed_Tics;
class Odometer_Tics;
class Odometer_Tics_Left_Right;
class Proxi_Left_Right;
class Milli_Amp;
class Odometer_Linear_Left_Right;
class Velocity_Angular_Left_Right;
class Velocity;

/*******************************************/
/* COMPOSED DATA TYPES INCLUDE FILES*/
/*******************************************/
#include "robotml/Header.h"
#include "robotml/MultiArrayDimension.h"
#include "robotml/MultiArrayLayout.h"
#include "robotml/ByteMultiArray.h"
#include "robotml/ColorRGBA.h"
#include "robotml/Float32MultiArray.h"
#include "robotml/Int32MultiArray.h"
#include "robotml/Int8MultiArray.h"
#include "robotml/Int16MultiArray.h"
#include "robotml/Int64MultiArray.h"
#include "robotml/Float64MultiArray.h"
#include "robotml/UInt64MultiArray.h"
#include "robotml/UIint16MultiArray.h"
#include "robotml/UInt32MultiArray.h"
#include "robotml/UInt8MultiArray.h"
#include "robotml/DiagnosticArray.h"
#include "robotml/KeyValue.h"
#include "robotml/DiagnosticStatus.h"
#include "robotml/Point.h"
#include "robotml/Point32.h"
#include "robotml/PointStamped.h"
#include "robotml/Polygon.h"
#include "robotml/PolygonStamped.h"
#include "robotml/Vector3.h"
#include "robotml/Vector3Stamped.h"
#include "robotml/Quaternion.h"
#include "robotml/Pose.h"
#include "robotml/PoseStamped.h"
#include "robotml/TwistWithCovariance.h"
#include "robotml/TwistStamped.h"
#include "robotml/Twist.h"
#include "robotml/PoseWithCovariance.h"
#include "robotml/Pose2D.h"
#include "robotml/PoseWithCovarianceStamped.h"
#include "robotml/PoseArray.h"
#include "robotml/QuaternionStamped.h"
#include "robotml/Transform.h"
#include "robotml/WrenchStamped.h"
#include "robotml/Wrench.h"
#include "robotml/Path.h"
#include "robotml/Odometry.h"
#include "robotml/MapMetaData.h"
#include "robotml/OccupancyGrid.h"
#include "robotml/GridCells.h"
#include "robotml/RegionOfInterest.h"
#include "robotml/Range.h"
#include "robotml/CameraInfo.h"
#include "robotml/Imu.h"
#include "robotml/LaserScan.h"
#include "robotml/Image.h"
#include "robotml/ChannelFloat32.h"
#include "robotml/CompressedImage.h"
#include "robotml/PointCloud.h"
#include "robotml/PointField.h"
#include "robotml/PointCloud2.h"
#include "robotml/JointState.h"
#include "robotml/NavSatStatus.h"
#include "robotml/NavSatFix.h"
#include "robotml/Joy.h"
#include "robotml/JoyFeedback.h"
#include "robotml/JoyFeedbackArray.h"
#include "robotml/CarLikeOdometry.h"
#include "robotml/DifferentialOdometry.h"
#include "robotml/COVARIANCE_TYPE.h"
#include "robotml/SERVICE_TYPE.h"
#include "robotml/STATUS_TYPE.h"
#include "robotml/GoalID.h"
#include "robotml/GoalStatus.h"
#include "robotml/GoalStatusArray.h"
#include "robotml/Velocity_Linear.h"
#include "robotml/Art_Set_Point.h"
#include "robotml/Distance.h"
#include "robotml/Metric.h"
#include "robotml/Angular.h"
#include "robotml/Velocity_Angular.h"
#include "robotml/Op_Set_Point.h"
#include "robotml/Speed_Tics_Left_Right.h"
#include "robotml/Speed_Tics.h"
#include "robotml/Odometer_Tics.h"
#include "robotml/Odometer_Tics_Left_Right.h"
#include "robotml/Proxi_Left_Right.h"
#include "robotml/Milli_Amp.h"
#include "robotml/Odometer_Linear_Left_Right.h"
#include "robotml/Velocity_Angular_Left_Right.h"
#include "robotml/Velocity.h"

#endif //__MAPS_ROBOTML_DATATYPES_H__
