/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ui.internal.AthenaDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AthenaDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AthenaDSLActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AthenaDSLActivator.getInstance().getInjector(AthenaDSLActivator.ORG_XTEXT_ATHENADSL);
	}
	
}
