/*
* generated by Xtext
*/
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.AthenaDSLGrammarAccess;

public class AthenaDSLParser extends AbstractContentAssistParser {
	
	@Inject
	private AthenaDSLGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalAthenaDSLParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalAthenaDSLParser result = new org.xtext.ui.contentassist.antlr.internal.InternalAthenaDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getDataTypeAccess().getAlternatives(), "rule__DataType__Alternatives");
					put(grammarAccess.getFuncProcAccess().getAlternatives(), "rule__FuncProc__Alternatives");
					put(grammarAccess.getArgAccess().getModifierAlternatives_0_0(), "rule__Arg__ModifierAlternatives_0_0");
					put(grammarAccess.getStatementAccess().getCallAlternatives_0(), "rule__Statement__CallAlternatives_0");
					put(grammarAccess.getArchitectureElementAccess().getAlternatives(), "rule__ArchitectureElement__Alternatives");
					put(grammarAccess.getEventConditionAccess().getCondAlternatives_1_0(), "rule__EventCondition__CondAlternatives_1_0");
					put(grammarAccess.getEventConditionAccess().getAlternatives_2(), "rule__EventCondition__Alternatives_2");
					put(grammarAccess.getParameterDeclarationAccess().getAlternatives_5(), "rule__ParameterDeclaration__Alternatives_5");
					put(grammarAccess.getProjectAccess().getGroup(), "rule__Project__Group__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getLanguageDeclarationAccess().getGroup(), "rule__LanguageDeclaration__Group__0");
					put(grammarAccess.getDefineTypeAccess().getGroup(), "rule__DefineType__Group__0");
					put(grammarAccess.getValidityFunctionDeclarationAccess().getGroup(), "rule__ValidityFunctionDeclaration__Group__0");
					put(grammarAccess.getBasicTypeAccess().getGroup(), "rule__BasicType__Group__0");
					put(grammarAccess.getIncludeDeclAccess().getGroup(), "rule__IncludeDecl__Group__0");
					put(grammarAccess.getLanguageDeclAccess().getGroup(), "rule__LanguageDecl__Group__0");
					put(grammarAccess.getLexicalCastDeclAccess().getGroup(), "rule__LexicalCastDecl__Group__0");
					put(grammarAccess.getArrayTypeAccess().getGroup(), "rule__ArrayType__Group__0");
					put(grammarAccess.getArrayTypeAccess().getGroup_7(), "rule__ArrayType__Group_7__0");
					put(grammarAccess.getVectorTypeAccess().getGroup(), "rule__VectorType__Group__0");
					put(grammarAccess.getMapTypeAccess().getGroup(), "rule__MapType__Group__0");
					put(grammarAccess.getStructTypeAccess().getGroup(), "rule__StructType__Group__0");
					put(grammarAccess.getStructTypeAccess().getGroup_2(), "rule__StructType__Group_2__0");
					put(grammarAccess.getStructTypeAccess().getGroup_2_2(), "rule__StructType__Group_2_2__0");
					put(grammarAccess.getStructElementAccess().getGroup(), "rule__StructElement__Group__0");
					put(grammarAccess.getStructElementAccess().getGroup_1(), "rule__StructElement__Group_1__0");
					put(grammarAccess.getStructElementAccess().getGroup_1_2(), "rule__StructElement__Group_1_2__0");
					put(grammarAccess.getStructElementAccess().getGroup_3(), "rule__StructElement__Group_3__0");
					put(grammarAccess.getIndexAccess().getGroup(), "rule__Index__Group__0");
					put(grammarAccess.getIndexAccess().getGroup_1(), "rule__Index__Group_1__0");
					put(grammarAccess.getUnionTypeAccess().getGroup(), "rule__UnionType__Group__0");
					put(grammarAccess.getUnionTypeAccess().getGroup_4(), "rule__UnionType__Group_4__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup(), "rule__FunctionDeclaration__Group__0");
					put(grammarAccess.getArgumentsDeclarationAccess().getGroup(), "rule__ArgumentsDeclaration__Group__0");
					put(grammarAccess.getArgAccess().getGroup(), "rule__Arg__Group__0");
					put(grammarAccess.getProcessingDeclarationAccess().getGroup(), "rule__ProcessingDeclaration__Group__0");
					put(grammarAccess.getLocalParameterDeclarationAccess().getGroup(), "rule__LocalParameterDeclaration__Group__0");
					put(grammarAccess.getLocalParameterDeclarationAccess().getGroup_3(), "rule__LocalParameterDeclaration__Group_3__0");
					put(grammarAccess.getIfblockAccess().getGroup(), "rule__Ifblock__Group__0");
					put(grammarAccess.getIfblockAccess().getGroup_6(), "rule__Ifblock__Group_6__0");
					put(grammarAccess.getWhileblockAccess().getGroup(), "rule__Whileblock__Group__0");
					put(grammarAccess.getFunctionCallAccess().getGroup(), "rule__FunctionCall__Group__0");
					put(grammarAccess.getFunctionCallAccess().getGroup_3(), "rule__FunctionCall__Group_3__0");
					put(grammarAccess.getFunctionCallAccess().getGroup_3_1(), "rule__FunctionCall__Group_3_1__0");
					put(grammarAccess.getPrototypeDeclarationAccess().getGroup(), "rule__PrototypeDeclaration__Group__0");
					put(grammarAccess.getPrototypeDeclarationAccess().getGroup_2(), "rule__PrototypeDeclaration__Group_2__0");
					put(grammarAccess.getSignalDeclarationAccess().getGroup(), "rule__SignalDeclaration__Group__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup(), "rule__EventDeclaration__Group__0");
					put(grammarAccess.getEventDeclarationAccess().getGroup_4(), "rule__EventDeclaration__Group_4__0");
					put(grammarAccess.getEventConditionAccess().getGroup(), "rule__EventCondition__Group__0");
					put(grammarAccess.getParameterDeclarationAccess().getGroup(), "rule__ParameterDeclaration__Group__0");
					put(grammarAccess.getParameterDeclarationAccess().getGroup_2(), "rule__ParameterDeclaration__Group_2__0");
					put(grammarAccess.getParameterDeclarationAccess().getGroup_5_0(), "rule__ParameterDeclaration__Group_5_0__0");
					put(grammarAccess.getParameterDeclarationAccess().getGroup_5_1(), "rule__ParameterDeclaration__Group_5_1__0");
					put(grammarAccess.getParameterDeclarationAccess().getGroup_5_2(), "rule__ParameterDeclaration__Group_5_2__0");
					put(grammarAccess.getStatesetDeclarationAccess().getGroup(), "rule__StatesetDeclaration__Group__0");
					put(grammarAccess.getStatesetDeclarationAccess().getGroup_6(), "rule__StatesetDeclaration__Group_6__0");
					put(grammarAccess.getTransitionDeclarationAccess().getGroup(), "rule__TransitionDeclaration__Group__0");
					put(grammarAccess.getTransitionDeclarationAccess().getGroup_7(), "rule__TransitionDeclaration__Group_7__0");
					put(grammarAccess.getInstanceDeclarationAccess().getGroup(), "rule__InstanceDeclaration__Group__0");
					put(grammarAccess.getInteractionDeclarationAccess().getGroup(), "rule__InteractionDeclaration__Group__0");
					put(grammarAccess.getInteractionDeclarationAccess().getGroup_0(), "rule__InteractionDeclaration__Group_0__0");
					put(grammarAccess.getInteractionDeclarationAccess().getGroup_1(), "rule__InteractionDeclaration__Group_1__0");
					put(grammarAccess.getInteractionCallAccess().getGroup(), "rule__InteractionCall__Group__0");
					put(grammarAccess.getInteractionCallAccess().getGroup_3(), "rule__InteractionCall__Group_3__0");
					put(grammarAccess.getInteractionCallAccess().getGroup_3_1(), "rule__InteractionCall__Group_3_1__0");
					put(grammarAccess.getReferenceDeclarationAccess().getGroup(), "rule__ReferenceDeclaration__Group__0");
					put(grammarAccess.getReferenceDeclarationAccess().getGroup_6(), "rule__ReferenceDeclaration__Group_6__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup(), "rule__WrapperDeclaration__Group__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_9(), "rule__WrapperDeclaration__Group_9__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_9_1(), "rule__WrapperDeclaration__Group_9_1__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_13(), "rule__WrapperDeclaration__Group_13__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_13_1(), "rule__WrapperDeclaration__Group_13_1__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_17(), "rule__WrapperDeclaration__Group_17__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_17_1(), "rule__WrapperDeclaration__Group_17_1__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_21(), "rule__WrapperDeclaration__Group_21__0");
					put(grammarAccess.getWrapperDeclarationAccess().getGroup_21_1(), "rule__WrapperDeclaration__Group_21_1__0");
					put(grammarAccess.getProjectAccess().getImportsAssignment_0(), "rule__Project__ImportsAssignment_0");
					put(grammarAccess.getProjectAccess().getLanguagesAssignment_1(), "rule__Project__LanguagesAssignment_1");
					put(grammarAccess.getProjectAccess().getTypesAssignment_2(), "rule__Project__TypesAssignment_2");
					put(grammarAccess.getProjectAccess().getValiditiesAssignment_3(), "rule__Project__ValiditiesAssignment_3");
					put(grammarAccess.getProjectAccess().getImportsAssignment_4(), "rule__Project__ImportsAssignment_4");
					put(grammarAccess.getProjectAccess().getFunctionsAssignment_5(), "rule__Project__FunctionsAssignment_5");
					put(grammarAccess.getProjectAccess().getImportsAssignment_6(), "rule__Project__ImportsAssignment_6");
					put(grammarAccess.getProjectAccess().getProcessingsAssignment_7(), "rule__Project__ProcessingsAssignment_7");
					put(grammarAccess.getProjectAccess().getImportsAssignment_8(), "rule__Project__ImportsAssignment_8");
					put(grammarAccess.getProjectAccess().getPrototypesAssignment_9(), "rule__Project__PrototypesAssignment_9");
					put(grammarAccess.getProjectAccess().getImportsAssignment_10(), "rule__Project__ImportsAssignment_10");
					put(grammarAccess.getProjectAccess().getWrappersAssignment_11(), "rule__Project__WrappersAssignment_11");
					put(grammarAccess.getImportAccess().getImportURIAssignment_1(), "rule__Import__ImportURIAssignment_1");
					put(grammarAccess.getLanguageDeclarationAccess().getNameAssignment_1(), "rule__LanguageDeclaration__NameAssignment_1");
					put(grammarAccess.getDefineTypeAccess().getNameAssignment_1(), "rule__DefineType__NameAssignment_1");
					put(grammarAccess.getDefineTypeAccess().getTypenameAssignment_3(), "rule__DefineType__TypenameAssignment_3");
					put(grammarAccess.getValidityFunctionDeclarationAccess().getTypenameAssignment_1(), "rule__ValidityFunctionDeclaration__TypenameAssignment_1");
					put(grammarAccess.getValidityFunctionDeclarationAccess().getFctNameAssignment_2(), "rule__ValidityFunctionDeclaration__FctNameAssignment_2");
					put(grammarAccess.getBasicTypeAccess().getNameAssignment_1(), "rule__BasicType__NameAssignment_1");
					put(grammarAccess.getBasicTypeAccess().getIncludesAssignment_3(), "rule__BasicType__IncludesAssignment_3");
					put(grammarAccess.getBasicTypeAccess().getLanguagesAssignment_4(), "rule__BasicType__LanguagesAssignment_4");
					put(grammarAccess.getBasicTypeAccess().getCastsAssignment_5(), "rule__BasicType__CastsAssignment_5");
					put(grammarAccess.getIncludeDeclAccess().getLangAssignment_1(), "rule__IncludeDecl__LangAssignment_1");
					put(grammarAccess.getIncludeDeclAccess().getIncludeNameAssignment_3(), "rule__IncludeDecl__IncludeNameAssignment_3");
					put(grammarAccess.getLanguageDeclAccess().getLangAssignment_1(), "rule__LanguageDecl__LangAssignment_1");
					put(grammarAccess.getLanguageDeclAccess().getTransAssignment_3(), "rule__LanguageDecl__TransAssignment_3");
					put(grammarAccess.getLanguageDeclAccess().getValueAssignment_5(), "rule__LanguageDecl__ValueAssignment_5");
					put(grammarAccess.getLexicalCastDeclAccess().getLangAssignment_1(), "rule__LexicalCastDecl__LangAssignment_1");
					put(grammarAccess.getLexicalCastDeclAccess().getCastAssignment_3(), "rule__LexicalCastDecl__CastAssignment_3");
					put(grammarAccess.getArrayTypeAccess().getTypenameAssignment_2(), "rule__ArrayType__TypenameAssignment_2");
					put(grammarAccess.getArrayTypeAccess().getNameAssignment_4(), "rule__ArrayType__NameAssignment_4");
					put(grammarAccess.getArrayTypeAccess().getIndicesAssignment_6(), "rule__ArrayType__IndicesAssignment_6");
					put(grammarAccess.getArrayTypeAccess().getIndicesAssignment_7_1(), "rule__ArrayType__IndicesAssignment_7_1");
					put(grammarAccess.getVectorTypeAccess().getTypenameAssignment_2(), "rule__VectorType__TypenameAssignment_2");
					put(grammarAccess.getVectorTypeAccess().getNameAssignment_4(), "rule__VectorType__NameAssignment_4");
					put(grammarAccess.getMapTypeAccess().getKeytypeAssignment_2(), "rule__MapType__KeytypeAssignment_2");
					put(grammarAccess.getMapTypeAccess().getValtypeAssignment_4(), "rule__MapType__ValtypeAssignment_4");
					put(grammarAccess.getMapTypeAccess().getNameAssignment_6(), "rule__MapType__NameAssignment_6");
					put(grammarAccess.getStructTypeAccess().getNameAssignment_1(), "rule__StructType__NameAssignment_1");
					put(grammarAccess.getStructTypeAccess().getIndicesAssignment_2_1(), "rule__StructType__IndicesAssignment_2_1");
					put(grammarAccess.getStructTypeAccess().getIndicesAssignment_2_2_1(), "rule__StructType__IndicesAssignment_2_2_1");
					put(grammarAccess.getStructTypeAccess().getParametersAssignment_4(), "rule__StructType__ParametersAssignment_4");
					put(grammarAccess.getStructElementAccess().getTypenameAssignment_0(), "rule__StructElement__TypenameAssignment_0");
					put(grammarAccess.getStructElementAccess().getIndicesAssignment_1_1(), "rule__StructElement__IndicesAssignment_1_1");
					put(grammarAccess.getStructElementAccess().getIndicesAssignment_1_2_1(), "rule__StructElement__IndicesAssignment_1_2_1");
					put(grammarAccess.getStructElementAccess().getNameAssignment_2(), "rule__StructElement__NameAssignment_2");
					put(grammarAccess.getStructElementAccess().getHasInitValueAssignment_3_0(), "rule__StructElement__HasInitValueAssignment_3_0");
					put(grammarAccess.getStructElementAccess().getInitValueAssignment_3_1(), "rule__StructElement__InitValueAssignment_3_1");
					put(grammarAccess.getIndexAccess().getDimAssignment_0(), "rule__Index__DimAssignment_0");
					put(grammarAccess.getIndexAccess().getHasValueAssignment_1_0(), "rule__Index__HasValueAssignment_1_0");
					put(grammarAccess.getIndexAccess().getValueAssignment_1_1(), "rule__Index__ValueAssignment_1_1");
					put(grammarAccess.getUnionTypeAccess().getNameAssignment_1(), "rule__UnionType__NameAssignment_1");
					put(grammarAccess.getUnionTypeAccess().getElementsAssignment_3(), "rule__UnionType__ElementsAssignment_3");
					put(grammarAccess.getUnionTypeAccess().getElementsAssignment_4_1(), "rule__UnionType__ElementsAssignment_4_1");
					put(grammarAccess.getFunctionDeclarationAccess().getNameAssignment_1(), "rule__FunctionDeclaration__NameAssignment_1");
					put(grammarAccess.getFunctionDeclarationAccess().getLangAssignment_3(), "rule__FunctionDeclaration__LangAssignment_3");
					put(grammarAccess.getFunctionDeclarationAccess().getArgsAssignment_6(), "rule__FunctionDeclaration__ArgsAssignment_6");
					put(grammarAccess.getArgumentsDeclarationAccess().getArgumentsAssignment_0(), "rule__ArgumentsDeclaration__ArgumentsAssignment_0");
					put(grammarAccess.getArgumentsDeclarationAccess().getArgumentsAssignment_1(), "rule__ArgumentsDeclaration__ArgumentsAssignment_1");
					put(grammarAccess.getArgAccess().getModifierAssignment_0(), "rule__Arg__ModifierAssignment_0");
					put(grammarAccess.getArgAccess().getTypeAssignment_1(), "rule__Arg__TypeAssignment_1");
					put(grammarAccess.getArgAccess().getNameAssignment_2(), "rule__Arg__NameAssignment_2");
					put(grammarAccess.getProcessingDeclarationAccess().getNameAssignment_1(), "rule__ProcessingDeclaration__NameAssignment_1");
					put(grammarAccess.getProcessingDeclarationAccess().getArgsAssignment_3(), "rule__ProcessingDeclaration__ArgsAssignment_3");
					put(grammarAccess.getProcessingDeclarationAccess().getLocalParametersAssignment_6(), "rule__ProcessingDeclaration__LocalParametersAssignment_6");
					put(grammarAccess.getProcessingDeclarationAccess().getLocalEventsAssignment_7(), "rule__ProcessingDeclaration__LocalEventsAssignment_7");
					put(grammarAccess.getProcessingDeclarationAccess().getStatementsAssignment_8(), "rule__ProcessingDeclaration__StatementsAssignment_8");
					put(grammarAccess.getStatementAccess().getCallAssignment(), "rule__Statement__CallAssignment");
					put(grammarAccess.getLocalParameterDeclarationAccess().getTypeAssignment_1(), "rule__LocalParameterDeclaration__TypeAssignment_1");
					put(grammarAccess.getLocalParameterDeclarationAccess().getNameAssignment_2(), "rule__LocalParameterDeclaration__NameAssignment_2");
					put(grammarAccess.getLocalParameterDeclarationAccess().getHasValueAssignment_3_0(), "rule__LocalParameterDeclaration__HasValueAssignment_3_0");
					put(grammarAccess.getLocalParameterDeclarationAccess().getValueAssignment_3_1(), "rule__LocalParameterDeclaration__ValueAssignment_3_1");
					put(grammarAccess.getIfblockAccess().getEventNameAssignment_1(), "rule__Ifblock__EventNameAssignment_1");
					put(grammarAccess.getIfblockAccess().getIfBlocksAssignment_4(), "rule__Ifblock__IfBlocksAssignment_4");
					put(grammarAccess.getIfblockAccess().getHasElseAssignment_6_0(), "rule__Ifblock__HasElseAssignment_6_0");
					put(grammarAccess.getIfblockAccess().getElseBlocksAssignment_6_2(), "rule__Ifblock__ElseBlocksAssignment_6_2");
					put(grammarAccess.getWhileblockAccess().getEventNameAssignment_1(), "rule__Whileblock__EventNameAssignment_1");
					put(grammarAccess.getWhileblockAccess().getBlocksAssignment_4(), "rule__Whileblock__BlocksAssignment_4");
					put(grammarAccess.getFunctionCallAccess().getNameAssignment_1(), "rule__FunctionCall__NameAssignment_1");
					put(grammarAccess.getFunctionCallAccess().getArgumentsAssignment_3_0(), "rule__FunctionCall__ArgumentsAssignment_3_0");
					put(grammarAccess.getFunctionCallAccess().getArgumentsAssignment_3_1_1(), "rule__FunctionCall__ArgumentsAssignment_3_1_1");
					put(grammarAccess.getPrototypeDeclarationAccess().getNameAssignment_1(), "rule__PrototypeDeclaration__NameAssignment_1");
					put(grammarAccess.getPrototypeDeclarationAccess().getSuperTypeAssignment_2_1(), "rule__PrototypeDeclaration__SuperTypeAssignment_2_1");
					put(grammarAccess.getPrototypeDeclarationAccess().getDefinitionsAssignment_4(), "rule__PrototypeDeclaration__DefinitionsAssignment_4");
					put(grammarAccess.getSignalDeclarationAccess().getNameAssignment_1(), "rule__SignalDeclaration__NameAssignment_1");
					put(grammarAccess.getEventDeclarationAccess().getNameAssignment_1(), "rule__EventDeclaration__NameAssignment_1");
					put(grammarAccess.getEventDeclarationAccess().getConditionsAssignment_3(), "rule__EventDeclaration__ConditionsAssignment_3");
					put(grammarAccess.getEventDeclarationAccess().getConditionsAssignment_4_1(), "rule__EventDeclaration__ConditionsAssignment_4_1");
					put(grammarAccess.getEventConditionAccess().getLeftPartAssignment_0(), "rule__EventCondition__LeftPartAssignment_0");
					put(grammarAccess.getEventConditionAccess().getCondAssignment_1(), "rule__EventCondition__CondAssignment_1");
					put(grammarAccess.getEventConditionAccess().getRightPartIAssignment_2_0(), "rule__EventCondition__RightPartIAssignment_2_0");
					put(grammarAccess.getEventConditionAccess().getRightPartNAssignment_2_1(), "rule__EventCondition__RightPartNAssignment_2_1");
					put(grammarAccess.getEventConditionAccess().getRightPartSAssignment_2_2(), "rule__EventCondition__RightPartSAssignment_2_2");
					put(grammarAccess.getParameterDeclarationAccess().getTypeNameAssignment_1(), "rule__ParameterDeclaration__TypeNameAssignment_1");
					put(grammarAccess.getParameterDeclarationAccess().getHasNbWAssignment_2_0(), "rule__ParameterDeclaration__HasNbWAssignment_2_0");
					put(grammarAccess.getParameterDeclarationAccess().getNbwAssignment_2_2(), "rule__ParameterDeclaration__NbwAssignment_2_2");
					put(grammarAccess.getParameterDeclarationAccess().getHasInfiniteWriterAssignment_3(), "rule__ParameterDeclaration__HasInfiniteWriterAssignment_3");
					put(grammarAccess.getParameterDeclarationAccess().getNameAssignment_4(), "rule__ParameterDeclaration__NameAssignment_4");
					put(grammarAccess.getParameterDeclarationAccess().getHasValueAssignment_5_0_0(), "rule__ParameterDeclaration__HasValueAssignment_5_0_0");
					put(grammarAccess.getParameterDeclarationAccess().getValueAssignment_5_0_1(), "rule__ParameterDeclaration__ValueAssignment_5_0_1");
					put(grammarAccess.getParameterDeclarationAccess().getHasConfigAssignment_5_1_0(), "rule__ParameterDeclaration__HasConfigAssignment_5_1_0");
					put(grammarAccess.getParameterDeclarationAccess().getHasConfigWithDefaultValueAssignment_5_2_0(), "rule__ParameterDeclaration__HasConfigWithDefaultValueAssignment_5_2_0");
					put(grammarAccess.getParameterDeclarationAccess().getValueAssignment_5_2_2(), "rule__ParameterDeclaration__ValueAssignment_5_2_2");
					put(grammarAccess.getStatesetDeclarationAccess().getNameAssignment_1(), "rule__StatesetDeclaration__NameAssignment_1");
					put(grammarAccess.getStatesetDeclarationAccess().getStatesAssignment_3(), "rule__StatesetDeclaration__StatesAssignment_3");
					put(grammarAccess.getStatesetDeclarationAccess().getStatesAssignment_5(), "rule__StatesetDeclaration__StatesAssignment_5");
					put(grammarAccess.getStatesetDeclarationAccess().getStatesAssignment_6_1(), "rule__StatesetDeclaration__StatesAssignment_6_1");
					put(grammarAccess.getStatesetDeclarationAccess().getInitAssignment_9(), "rule__StatesetDeclaration__InitAssignment_9");
					put(grammarAccess.getStatesetDeclarationAccess().getTransitionsAssignment_11(), "rule__StatesetDeclaration__TransitionsAssignment_11");
					put(grammarAccess.getStateDeclarationAccess().getNameAssignment(), "rule__StateDeclaration__NameAssignment");
					put(grammarAccess.getTransitionDeclarationAccess().getFromAssignment_2(), "rule__TransitionDeclaration__FromAssignment_2");
					put(grammarAccess.getTransitionDeclarationAccess().getToAssignment_4(), "rule__TransitionDeclaration__ToAssignment_4");
					put(grammarAccess.getTransitionDeclarationAccess().getEvtAssignment_6(), "rule__TransitionDeclaration__EvtAssignment_6");
					put(grammarAccess.getTransitionDeclarationAccess().getRaiseAssignment_7_0(), "rule__TransitionDeclaration__RaiseAssignment_7_0");
					put(grammarAccess.getTransitionDeclarationAccess().getSigAssignment_7_1(), "rule__TransitionDeclaration__SigAssignment_7_1");
					put(grammarAccess.getInstanceDeclarationAccess().getTypeNameAssignment_1(), "rule__InstanceDeclaration__TypeNameAssignment_1");
					put(grammarAccess.getInstanceDeclarationAccess().getNameAssignment_3(), "rule__InstanceDeclaration__NameAssignment_3");
					put(grammarAccess.getInteractionDeclarationAccess().getWwhenAssignment_0_0(), "rule__InteractionDeclaration__WwhenAssignment_0_0");
					put(grammarAccess.getInteractionDeclarationAccess().getStatesetAssignment_0_2(), "rule__InteractionDeclaration__StatesetAssignment_0_2");
					put(grammarAccess.getInteractionDeclarationAccess().getWstateAssignment_0_4(), "rule__InteractionDeclaration__WstateAssignment_0_4");
					put(grammarAccess.getInteractionDeclarationAccess().getIifAssignment_1_0(), "rule__InteractionDeclaration__IifAssignment_1_0");
					put(grammarAccess.getInteractionDeclarationAccess().getEventAssignment_1_2(), "rule__InteractionDeclaration__EventAssignment_1_2");
					put(grammarAccess.getInteractionDeclarationAccess().getIcallsAssignment_3(), "rule__InteractionDeclaration__IcallsAssignment_3");
					put(grammarAccess.getInteractionCallAccess().getFctNameAssignment_1(), "rule__InteractionCall__FctNameAssignment_1");
					put(grammarAccess.getInteractionCallAccess().getArgumentsAssignment_3_0(), "rule__InteractionCall__ArgumentsAssignment_3_0");
					put(grammarAccess.getInteractionCallAccess().getArgumentsAssignment_3_1_1(), "rule__InteractionCall__ArgumentsAssignment_3_1_1");
					put(grammarAccess.getFargAccess().getVarNameAssignment(), "rule__Farg__VarNameAssignment");
					put(grammarAccess.getReferenceDeclarationAccess().getTypeNameAssignment_2(), "rule__ReferenceDeclaration__TypeNameAssignment_2");
					put(grammarAccess.getReferenceDeclarationAccess().getUpwayAssignment_4(), "rule__ReferenceDeclaration__UpwayAssignment_4");
					put(grammarAccess.getReferenceDeclarationAccess().getNameAssignment_5(), "rule__ReferenceDeclaration__NameAssignment_5");
					put(grammarAccess.getReferenceDeclarationAccess().getAliasAssignment_6_1(), "rule__ReferenceDeclaration__AliasAssignment_6_1");
					put(grammarAccess.getQualifiedNameAccess().getNameAssignment_0(), "rule__QualifiedName__NameAssignment_0");
					put(grammarAccess.getQualifiedNameAccess().getNameAssignment_1_1(), "rule__QualifiedName__NameAssignment_1_1");
					put(grammarAccess.getWrapperDeclarationAccess().getNameAssignment_1(), "rule__WrapperDeclaration__NameAssignment_1");
					put(grammarAccess.getWrapperDeclarationAccess().getLinkAssignment_5(), "rule__WrapperDeclaration__LinkAssignment_5");
					put(grammarAccess.getWrapperDeclarationAccess().getFunctionsAssignment_9_0(), "rule__WrapperDeclaration__FunctionsAssignment_9_0");
					put(grammarAccess.getWrapperDeclarationAccess().getFunctionsAssignment_9_1_1(), "rule__WrapperDeclaration__FunctionsAssignment_9_1_1");
					put(grammarAccess.getWrapperDeclarationAccess().getObjectsAssignment_13_0(), "rule__WrapperDeclaration__ObjectsAssignment_13_0");
					put(grammarAccess.getWrapperDeclarationAccess().getObjectsAssignment_13_1_1(), "rule__WrapperDeclaration__ObjectsAssignment_13_1_1");
					put(grammarAccess.getWrapperDeclarationAccess().getLibrariesAssignment_17_0(), "rule__WrapperDeclaration__LibrariesAssignment_17_0");
					put(grammarAccess.getWrapperDeclarationAccess().getLibrariesAssignment_17_1_1(), "rule__WrapperDeclaration__LibrariesAssignment_17_1_1");
					put(grammarAccess.getWrapperDeclarationAccess().getTestsAssignment_21_0(), "rule__WrapperDeclaration__TestsAssignment_21_0");
					put(grammarAccess.getWrapperDeclarationAccess().getTestsAssignment_21_1_1(), "rule__WrapperDeclaration__TestsAssignment_21_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalAthenaDSLParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalAthenaDSLParser) parser;
			typedParser.entryRuleProject();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AthenaDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AthenaDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
