/*
* generated by Xtext
*/
package org.xtext.ui.contentassist;

import org.xtext.ui.contentassist.AbstractAthenaDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AthenaDSLProposalProvider extends AbstractAthenaDSLProposalProvider {

}
