/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AthenaDSLUiModule extends org.xtext.ui.AbstractAthenaDSLUiModule {
	public AthenaDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
